### ISSUE TITLE
pls. don't use relative path names for assets

### ISSUE THREAD

**Issue by philippfrenzel** [damiandennis/yii2-knockoutjs#1]
Hi, 

for adding the assets to the project, pls use the @bower or @npm alias for referencing to the root folder. If you take a look at the yii2 guide, they have some nice examples in how to include bower packages.

Regards Phil

**Comment by damiandennis** [comment]
thanks for that, I will fix it up shortly.

**Comment by damiandennis** [comment]
fixed in a1ab5d433ecdbd5d8a3ceccb892a1db0c87258a2
